---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: smarterp-backend
  namespace: smarterp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: smarterp
      app.kubernetes.io/component: backend
